name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Switch to nightly
      run: rustup install nightly && rustup default nightly
    - name: Run tests
      run: cargo x86-test --verbose
